---
groups:
  - name: all
    jobs:
      - build
      - list

resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: governmentpaas/s3-resource
    tag: initial_version

resources:
  - name: 46bit-master
    type: git
    source:
      uri: https://github.com/46bit/46b.it.git
      branch: master

  - name: 46bit-build
    type: git
    source:
      uri: https://github.com/46bit/46b.it.git
      branch: build

  # - name: terraform-state
  #   type: s3-iam
  #   source:
  #     bucket:
  #     versioned_file: vpc.tfstate
  #     region_name: ((aws_region))
  #     initial_version: "-"
  #     initial_content_text: |
  #       {
  #           "version": 1,
  #           "serial": 0,
  #           "modules": [
  #               {
  #                   "path": ["root"],
  #                   "outputs": {},
  #                   "resources": {},
  #                   "depends_on": []
  #               }
  #           ]
  #       }

jobs:
  - name: build
    serial: true
    plan:
      - aggregate:
        - get: 46bit-master
          trigger: true
        - get: 46bit-build

      - task: jekyll-build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jekyll/builder
              tag: 3.4.3
          inputs:
            - name: 46bit-master
            - name: 46bit-build
          outputs:
            - name: 46bit-build
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                cd 46bit-master
                CURRENT_REVISION=$(cat .git/ref)
                bundle install
                bundle exec jekyll build -d ../46bit-build/site
                cp -R terraform ../46bit-build/terraform

                cd ../46bit-build
                git add -A
                git commit --allow-empty -m "Built ${CURRENT_REVISION}"

      - put: 46bit-build

  - name: deploy
    serial: true
    plan:
      - aggregate:
        - get: 46b.it-site
          trigger: true
          passed: ['build']

      - task: terraform-apply
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/terraform
              tag: 9cad30b5d5889a0b72173f39701d1620e24df82c
          inputs:
            - name: 46bit-build
          run:
            path: sh
            args:
              - -e
              - -c
              - cd 46bit-build/terraform
                terraform apply

      - task: sync-to-s3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/terraform
              tag: 9cad30b5d5889a0b72173f39701d1620e24df82c
          inputs:
            - name: 46b.it-site
          run:
            path: sh
            args:
              - -e
              - -c
              - cd 46bit-build/site
                aws s3 sync . s3://miki-46bit --delete

      - task: expire-cloudfront-cache
